# Generated by Django 4.0.4 on 2022-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_index', models.CharField(default='', max_length=30)),
                ('Username', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=30)),
                ('images', models.ImageField(default='', upload_to='images_db')),
            ],
        ),
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geeks_field', models.BinaryField(editable=True)),
            ],
        ),
    ]
